### ISSUE TITLE
Erreur de compilation sur Signal

### ISSUE THREAD

**Issue by TheNawaKer** [GNU-Ymir/Ymir-Test#1]
Depuis la dernière mise à jour de Gyc, impossible de recompiler le code présent dans signal.
Erreur obtenu: 
`ymir1: fatal error: ['('] expected, when ) found
 --> main.yr:(13,36)
    | 
13  |         sig.func [it] (elems.expand);
    |       
`
![vmware_2018-04-12_22-54-07](https://user-images.githubusercontent.com/1174039/38703843-adcb515e-3ea4-11e8-9da7-d9579237b385.png)

**Comment by EmileCadorel** [comment]
il y a eu un petit changement de syntaxe, maintenant les `expand`, `typeof` et `stringof` s'ecrivent avec `::`
```
foo (a::expand);
foo!(a::typeof);
```
